# Generated by Django 5.2.4 on 2025-07-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_employeeprofile_qr_code_employeesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='permission_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('WFH', 'Work From Home'), ('Half Day', 'Half Day'), ('Permission', 'Permission')], max_length=20, null=True),
        ),
    ]
