# Generated by Django 5.2.4 on 2025-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_attendance_position_alter_attendance_permission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='permission_type',
            field=models.CharField(default='Present', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='position',
            field=models.CharField(default='Employee', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
