# Generated by Django 5.2.4 on 2025-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_attendance_permission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='permission_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
