# Generated by Django 5.2.4 on 2025-07-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_attendance_permission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
