# Generated by Django 5.2.4 on 2025-07-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_attendance_break_end_attendance_break_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='break_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='break_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
