# Generated by Django 5.2.4 on 2025-07-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_attendance_break_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
