# Generated by Django 5.2.4 on 2025-07-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_attendance_break_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('halfday', 'Half Day')], max_length=20),
        ),
    ]
