# Generated by Django 5.2.4 on 2025-07-30 05:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.DateTimeField(blank=True, default=accounts.models.default_10am, null=True),
        ),
    ]
