# Generated by Django 5.2.4 on 2025-07-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_attendance_punch_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='break_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
