# Generated by Django 5.1.5 on 2025-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_attendance_break_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='permission_type',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='position',
        ),
        migrations.AddField(
            model_name='attendance',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
