# Generated by Django 5.1.5 on 2025-07-31 12:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_attendance_permission_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='permission',
        ),
        migrations.AddField(
            model_name='attendance',
            name='permission_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.DateTimeField(blank=True, default=accounts.models.default_10am, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('halfday', 'Half Day')], max_length=20),
        ),
    ]
