# Generated by Django 5.1.5 on 2025-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_attendance_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='position',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='permission_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
