# Generated by Django 5.2.4 on 2025-08-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_attendance_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='position',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
