# Generated by Django 5.2.4 on 2025-08-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_attendance_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='permission_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
