# Generated by Django 5.2.4 on 2025-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_attendance_permission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='position',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
