# Generated by Django 5.2.4 on 2025-08-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_attendance_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
