# Generated by Django 5.2.4 on 2025-08-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_attendance_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='reason',
        ),
    ]
