# Generated by Django 5.2.4 on 2025-08-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_attendance_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
