# Generated by Django 5.2.4 on 2025-08-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Attendance Records'},
        ),
    ]
